### ISSUE TITLE
Errors on VS 2017 with current OF master

### ISSUE THREAD

**Issue by fred-dev** [bakercp/ofxNetworkUtils#2]
I have some errors on the current master with this addon. and in a strange way. I bypassed the OF version check first, and now the examples compile fine, but when I use this in combination with some other addons I get errors. My addons.make contains:

```
ofxHTTP
ofxIO
ofxMediaType
ofxNetwork
ofxNetworkUtils
ofxPoco
ofxSSLManager
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "int __cdecl ofxNetworkCheckErrno(char const *,int)" (?ofxNetworkCheckErrno@@YAHPEBDH@Z)	example	C:\Users\playback\Documents\openFrameworks\addons\ofxTwinkly\example\ofxTCPClient.obj	1	
Error	LNK2001	unresolved external symbol "int __cdecl ofxNetworkCheckErrno(char const *,int)" (?ofxNetworkCheckErrno@@YAHPEBDH@Z)	example	C:\Users\playback\Documents\openFrameworks\addons\ofxTwinkly\example\ofxTCPManager.obj	1	
Error	LNK2001	unresolved external symbol "int __cdecl ofxNetworkCheckErrno(char const *,int)" (?ofxNetworkCheckErrno@@YAHPEBDH@Z)	example	C:\Users\playback\Documents\openFrameworks\addons\ofxTwinkly\example\ofxUDPManager.obj	1	

```
These addons work fine on OSX, I only get these on windows, using the project generator and the master branch of OF.

**Comment by bakercp** [comment]
Hi, these errors reference ofxNetworkCheckErrno which is part of
ofxNetwork. Perhaps you can post an issue on the forum?

**Comment by fred-dev** [comment]
Sorry, my mistake, that explains a few things. I'll try sort it out on the forum.
