### ISSUE TITLE
VS 2017 + OF v0.11 - fatal error c1021

### ISSUE THREAD

**Issue by digitalcoleman** [bakercp/ofxNetworkUtils#3]
**Error	C1021	invalid preprocessor command 'warning'**

VS is throwing this error, which can be fixed by commenting out the warning like so:

`#elif (OFX_NETWORKUTILS_VERSION_MAJOR < OF_VERSION_MAJOR || OFX_NETWORKUTILS_VERSION_MINOR < OF_VERSION_MINOR)
   // #warning Your version of openFrameworks may be too new for this addon.
   // #warning Please try the stable branch of this addon or see the README.md for more info.
#endif`

in ofxNetworkUtils.cpp

It may be the case that I just need to turn this error off?

**Comment by roymacdonald** [comment]
Was going to post this same issue, as some ofxRunway users have reported [here](https://github.com/runwayml/ofxRunway/issues/11#issuecomment-582958583)
What should be the correct way to proceed without getting rid of this warnings. As well, I guess that `OFX_NETWORKUTILS_VERSION_*` might need some updating.

**Comment by bakercp** [comment]
Just pushed a fix for this by removing it.  It was an attempt to help people by creating warnings with mis-matches, but ... didn't seem to work consistently.

**Comment by roymacdonald** [comment]
Thanks!
